pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                npm ci
                '''
            }
        }

        stage('Run Playwright tests') {
            steps {
                sh '''
                npx playwright test
                '''
            }
        }
    }

    post {
        always {
            // 1 Jenkins-native test reporting (JUnit)
            junit 'test-results/results.xml'

            // 2 Clickable HTML report in Jenkins sidebar
            publishHTML([
                allowMissing: false,    // In Declarative Pipelines, publishHTML requires certain parameters. If even one required field is missing, Groovy fails at compile time — which is why: pipeline stops early; Playwright never gets to publish anything; Jenkins shows blank results
                alwaysLinkToLastBuild: true,    // In Declarative Pipelines, publishHTML requires certain parameters. If even one required field is missing, Groovy fails at compile time — which is why: pipeline stops early; Playwright never gets to publish anything; Jenkins shows blank results
                keepAll: true,  // In Declarative Pipelines, publishHTML requires certain parameters. If even one required field is missing, Groovy fails at compile time — which is why: pipeline stops early; Playwright never gets to publish anything; Jenkins shows blank results
                reportDir: 'playwright-report',     // folder generated by Playwright
                reportFiles: 'index.html',          // main HTML report file
                reportName: 'Playwright Report',    // shows as a link in Jenkins
                keepAll: true,                       // keep all builds' reports
                alwaysLinkToLastBuild: true         // quick access to latest
            ])

            archiveArtifacts artifacts: 'playwright-report/**', fingerprint: true
        }
    }
}